 id |     name      |                                                                     description                                                                      |     image     | price_cents | quantity |         created_at         |         updated_at         | category_id 
----+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+-------------+----------+----------------------------+----------------------------+-------------
 10 | Eesrorn       | The Eesrorn is a very common, tall plant and can be found in most subarctic regions. It blooms twice a year, for 2 months.                          +| plante_10.jpg |        3999 |      320 | 2023-03-08 22:18:02.13779  | 2023-03-08 22:18:02.13779  |           3
    |               |   It has large, needle leaves, which are usually light yellow. It also grows decent sized flowers, which can be light grey, yellow and light blue.  +|               |             |          |                            |                            | 
    |               |                                                                                                                                                     +|               |             |          |                            |                            | 
    |               |   These plants grow separated by a fair distance from each other, but it's hard to control and maintain their growth.                               +|               |             |          |                            |                            | 
    |               |   They have no real use.                                                                                                                            +|               |             |          |                            |                            | 
    |               |                                                                                                                                                     +|               |             |          |                            |                            | 
    |               |   As a defense mechanism the Eesrorn has a thick, wooden stem.                                                                                      +|               |             |          |                            |                            | 
    |               |   They rely on water currents to carry their seeds away to reproduce. Once pollinated, they grow fairly large, inedible fruits.                      |               |             |          |                            |                            | 
 12 | Cliff Collard | The Cliff Collard is a very rare, tiny plant and can be found in damp places. It blooms twice a year, for 1 week.                                   +| plante_12.jpg |        7999 |       23 | 2023-03-08 22:18:02.377145 | 2023-03-08 22:18:02.377145 |           3
    |               |   It has wide, spear shaped leaves, which are usually lime green. It also grows quite large flowers, which can be silver, light brown and light red.+|               |             |          |                            |                            | 
    |               |                                                                                                                                                     +|               |             |          |                            |                            | 
    |               |   These plants grow within short distances from each other, but it's fairly hard to control and maintain their growth.                              +|               |             |          |                            |                            | 
    |               |   They can be brewed as tea.                                                                                                                        +|               |             |          |                            |                            | 
    |               |                                                                                                                                                     +|               |             |          |                            |                            | 
    |               |   As a defense mechanism the Cliff Collard grows thick thorns.                                                                                      +|               |             |          |                            |                            | 
    |               |   They rely on winds to carry their seeds away to reproduce. Once pollinated, they grow small, inedible fruits.                                      |               |             |          |                            |                            | 
(2 rows)

